### ISSUE TITLE
Move from APT to Javac to work with Java 8

### ISSUE THREAD

**Issue by jereitz** [stoicflame/enunciate#68]
From [ENUNCIATE-701](https://jira.codehaus.org/browse/ENUNCIATE-701):
JDK 1.7 displays the following warning when using maven-enunciate-plugin 1.27:
>    [INFO] invoking enunciate:generate step...
>    warning: The apt tool and its associated API are planned to be removed in the next major JDK 
>release. These features have been superseded by javac and the standardized annotation processing 
>API, javax.annotation.processing and javax.lang.model. Users are recommended to migrate to the 
>annotation processing features of javac; see the javac man page for more information.*

In JDK 1.8 however, you get this:
>Caused by: java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
>    at org.codehaus.enunciate.DocsMojo.loadMavenSpecificEnunciate(DocsMojo.java:107)
>    at org.codehaus.enunciate.ConfigMojo.execute(ConfigMojo.java:326)
>    at org.codehaus.enunciate.DocsMojo.execute(DocsMojo.java:81)
>    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
>    ... 20 more
>Caused by: java.lang.ClassNotFoundException: com.sun.mirror.apt.AnnotationProcessorFactory
>    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
 >   at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
>    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
>    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
>    ... 24 more

This is preventing projects from upgrading to Java 8.
See this [discussion](http://markmail.org/thread/npdawa334zqj3udr#query:+page:1+mid:zn4iwho3bn6drgjt+state:results) for more info.

**Comment by stoicflame** [comment]
Yes, this is priority 1 at the moment.

**Comment by stokito** [comment]
Hi @stoicflame 
I need this right now and I can contribute: I familiar with JSR 166 and annotation processing. Did you created any branch to work on this issue?
If not, I'll fork and start tomorrow

**Comment by stokito** [comment]
I found that you created [branch v2](https://github.com/stoicflame/enunciate/commits/v2) for fixing it.

**Comment by stoicflame** [comment]
Awesome!

I’ve been working on Enunciate 2 on the “v2” branch. As you noticed, it’s in its infancy right now. My thinking was that since it’s such a significant overhaul, I would try to completely replace the engine and model framework, but try to keep the generated templates and modules. Since “v2” is a pretty significant overhaul, I’m starting from “core” and I’ll add the other modules as I go.

What I need to do is break down the “v2” work into succinct tasks that I might be able to assign out. I never really bothered because I wasn’t expecting help. In the past, there haven’t been many people offer to help, so getting the project into a state where all the environment/project setup tasks are complete has never really been a priority.

Thanks again. I’ll let you know when I’ve got the “v2” work better documented and broken down into more manageable units.

**Comment by pjohnson-ptc** [comment]
Thanks for the status update on v2 for this project, we will keep on eye out also ... we are on java8 and have disabled our enunciate generation; which is unfortunate.

**Comment by oluwasayo** [comment]
I couldn't get it to work with Oracle JDK 1.7.0_55 too. Please see http://stackoverflow.com/questions/29720926/rest-documentation-with-enunciate-using-ant-task

Here's what I get:
java.lang.NoSuchMethodError: com.sun.tools.apt.util.Bark.printLines(Ljava/io/PrintWriter;Ljava/lang/String;)V
	at com.sun.tools.apt.main.Main.bugMessage(Main.java:1186)
	at com.sun.tools.apt.main.Main.compile(Main.java:831)
	at com.sun.tools.apt.Main.processing(Main.java:113)
	at com.sun.tools.apt.Main.process(Main.java:103)
	at com.sun.tools.apt.Main.process(Main.java:85)
	at org.codehaus.enunciate.main.Enunciate.invokeApt(Enunciate.java:817)
	at org.codehaus.enunciate.main.Enunciate.doGenerate(Enunciate.java:401)
	at org.codehaus.enunciate.main.Enunciate$Stepper.step(Enunciate.java:1799)
	at org.codehaus.enunciate.main.Enunciate$Stepper.stepTo(Enunciate.java:1831)
	at org.codehaus.enunciate.main.Enunciate.execute(Enunciate.java:181)
	at org.codehaus.enunciate.main.EnunciateTask.execute(EnunciateTask.java:170)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor825.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)

**Comment by stokito** [comment]
As temporary workaround we can compile Enunciate dependent modules with older JDK6 and reuse them under JDK8. But for Maven multi-module projects it needs to make plugin toolchain compatible as I described in #79

**Comment by stoicflame** [comment]
Hi @oluwasayo. I don't recognize that error, and it probably belongs in a separate thread. Will you [open up a separate issue](https://github.com/stoicflame/enunciate/issues/new)?

**Comment by jholdstock** [comment]
Hey @stoicflame - any news on how v2 is coming along? Did you manage to break down the workload?

**Comment by stoicflame** [comment]
I'm actively working on v2, as you can see by [the commit history](https://github.com/stoicflame/enunciate/commits/v2). My plan is to get the core ported over first, then I can put together the task list.

**Comment by stoicflame** [comment]
Okay, I've got a tentative roadmap with estimates laid out for this effort at [this Google Document](https://docs.google.com/spreadsheets/d/1mgo0DmvS0BsIOHdCL5tUeQcmqbKV2L_tvTBC5Rdibto/edit?usp=sharing).

I'm open to comments about the plan, including comments on my thoughts about what modules I'm thinking of porting to 2.0.

I'm thinking that it would be most effective for me to at least finish the "green" tasks by myself, and then we'll be in a good position to ask for contributions to refactor the "yellow" tasks.

**Comment by pjohnson-ptc** [comment]
10

J2EE Webapp Module

11

Documentation Module

12

IDL Module (was XML module)

13

Java Client Module


I would imagine are the most vital … but I could be wrong.

**Comment by leonard84** [comment]
We use only the documentation/IDL modules in our projects.

**Comment by cornelcreanga** [comment]
Hi @stoicflame, 
Is it possible to obtain a rough estimation regarding the V2 release date?
Thanks.

**Comment by stoicflame** [comment]
I'm probably still a month out. It depends a lot on how much time I can scrape up for it.

**Comment by leonard84** [comment]
Do you want to release enunciate 2.0 only if the yellow modules are complete? Why not release a version 2.0 with just the green core and add the yellow modules when they get done. The modules should be separate jars anyway.

**Comment by stoicflame** [comment]
Yes, I'll cut a milestone release when the green is finished.

**Comment by ligerdave** [comment]
Is there a work around for this? I kinda need it now... or is there a planned release date for the fix?

**Comment by stoicflame** [comment]
Status is still being maintained at the google doc.

https://docs.google.com/spreadsheets/d/1mgo0DmvS0BsIOHdCL5tUeQcmqbKV2L_tvTBC5Rdibto/edit#gid=0

**Comment by leonard84** [comment]
So we have 10 days of planned effort left until the first milestone release. The question is, how does it translate to real time? Is it like two weeks or more like two months?

**Comment by stoicflame** [comment]
A quick calculation shows that has taken 35 "real" (business) days to finish 28 estimated days of work so far. So that's about 1.25 of "real" days for each estimated day. So assuming the same rate, 10 days of work will take about 12.5 "real" days. So assuming the same rate and patterns, it looks like that first milestone might be expected around July 10th-ish.

**Comment by stoicflame** [comment]
I'm happy to finally announce the availability of the [Enunciate 2.0 Milestone 1 release](https://github.com/stoicflame
/enunciate/releases/tag/v2.0.0-M.1). Please try it out!

I'm sure there are a lot of bugs, so please report them, but note that Milestone 1 still doesn't include support for client-side libraries yet; it just generates the HTML documentation.

**Comment by stokito** [comment]
Great! BTW this is correct ling to release https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.1

I'll test it on this week.

Thanks :-)

**Comment by jellenelis** [comment]
I tried the 2.0 milestone and everything seems to work for me. However, is there a way to include the documentation in the maven site process, because I am not able to get this to work (no documenation about that on the milestone page, as documented on https://github.com/stoicflame/enunciate/wiki/Documentation-Only for earlier versions).

**Comment by stoicflame** [comment]
[Enunciate 2.0 Milestone 2 is now available.](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.2)

As always, any help in reporting bugs and other issues is appreciated.

Enunciate 2.0 Milestone 2 Includes:

* All the features of 2.0 Milestone 1
* A bunch of bug fixes (and appreciation for those who reported them)
* IDL Support (e.g. XML Schema, WSDL, WADL)
* Java XML Client Support
* Java JSON Client Support
* Support for configuring the documentation output directory in the Maven plugin.

**Comment by stoicflame** [comment]
@jellenelis: we'll track the work to make the plugin integrated with Maven site process at #106.

**Comment by jellenelis** [comment]
@stoicflame thanks

**Comment by stoicflame** [comment]
[Enunciate 2.0 Milestone 3 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.3).

Again, any help in reporting bugs and other issues is appreciated.

Enunciate 2.0 Milestone 3 includes:

* All the features of 2.0 Milestone 1
* All the features of 2.0 Milestone 2
* [A bunch of bug fixes](https://github.com/stoicflame/enunciate/issues?q=milestone%3Av2.0.0.M3) (and appreciation for those who reported them)
* Support for generating the C# XML client
* Support for generating the C/C++ XML client
* Support for generating the Objective C XML client
* Support for generating the PHP XML client
* Support for generating the PHP JSON client
* Support for generating the Ruby JSON client
* Support for including the Swagger UI
* More maven plugin enhancements:
  * [Support for using Enunciate as a custom report plugin](https://github.com/stoicflame/enunciate/issues/106)
  * Support for install and deploy client-side artifacts.
* Some smarter default settings for the generated documentation.
* Enabled some testing that has been disabled since the branch.

**Comment by anton-johansson** [comment]
Hi!

I'd love to try out the milestone releases (just came back from vacation), but I'm having some trouble getting it to work. Our previous Maven configuration looked like this:
```xml
			<plugin>
		       <groupId>org.codehaus.enunciate</groupId>
		       <artifactId>maven-enunciate-cxf-plugin</artifactId>
		       <version>1.29</version>
		       <configuration>
					<javacSourceVersion>1.7</javacSourceVersion>
        	   		<javacTargetVersion>1.7</javacTargetVersion>
        	   		<javacCheck>true</javacCheck>
              		<docsDir>${project.build.directory}/docs</docsDir>
              		<configFile>src/main/resources/enunciate/enunciate.xml</configFile>
               </configuration>
			</plugin>
```

... and using the exact same code but with the Milestone 3 version doesn't work out. Looking at your example in the release details, I should use the assemble goal, but I never seem to learn how the Maven lifecycle works 100%.

**Comment by storysj** [comment]
@anton-johansson, I was just having the same problem. You need to change your groupId to be: com.webcohesion.enunciate, since that's the group it's listed under in the maven central repo. See the milestone release notes for an example: https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.1

**Comment by anton-johansson** [comment]
Yeah, that I'm aware of, but it still wouldn't generate docs. I don't have the error I was getting right now, but I'll check again tomorrow.

Thanks though!

**Comment by stoicflame** [comment]
You also have to be aware that the `maven-enunciate-cxf-plugin` isn't supported anymore; it's the `enunciate-maven-plugin`.

Also, the `javacCheck` property isn't needed anymore, and the `javacSourceVersion` and `javacTargetVersion` have been shortened to `source` and `target`, respectively. But in the upcoming milestone 4 release, they might not be needed anymore either, since by default we'll just use the same source and target as the maven-compiler-plugin.

Also note that the configuration file has changed a lot, so you'll need to update that according to the latest schemas (e.g. [enunciate-2.0.0-M.3.xsd](http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.3.xsd)).

All this will be more clear as documentation (including a migration guide) becomes available. I'm working on that right now.

**Comment by anton-johansson** [comment]
Yeah I figured more documentation will come, I just wanted to get it working so I could contribute with potential bugs. :)

I'll see if I can get it working with the details you've supplied tomorrow! Thanks. :)

**Comment by anton-johansson** [comment]
Ok, I got it working now, here's what I had to do:

pom.xml:
```xml
<plugin>
	<groupId>com.webcohesion.enunciate</groupId>
	<artifactId>enunciate-maven-plugin</artifactId>
	<version>2.0.0-M.3</version>
	<executions>
		<execution>
			<id>docs</id>
			<goals>
				<goal>docs</goal>
			</goals>
			<configuration>
				<source>1.7</source>
       	   			<target>1.7</target>
			</configuration>
		</execution>
	</executions>
</plugin>
```

enunciate.xml:
```xml
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.4.xsd">

	<modules>
		<c-xml-client disabled="true" />
		<obj-c-xml-client disabled="true" />
		<swagger disabled="true" />
	</modules>

</enunciate>
```

I couldn't use assemble, since my artifact isn't of type ```war```, it's just a regular OSGi bundle.

Really, I don't want any clients generated, but just to demonstrate, I had to disable c-xml-client and obj-c-xml-client to get things working. Also swagger didn't work properly, however I like the non-swagger documentation better.

Do you want me to open up issues for the problems I got with c-xml-client and obj-c-xml-client?

**Comment by stoicflame** [comment]
Awesome, thanks for the report.

> Do you want me to open up issues for the problems I got with c-xml-client and obj-c-xml-client?

Yes, please!

> swagger didn't work properly

I'd also like to see a report on that, if you're willing.

I also opened up #127 to reconsider whether we really need two separate goals (assemble and docs) anymore.

**Comment by anton-johansson** [comment]
Allright, I'll see if I can get those reports up later today!

**Comment by anton-johansson** [comment]
See #128, #129 and #130.

**Comment by markBowman** [comment]
We use enunciate 1.28 in a number of projects. We are finally moving from Java6 to Java8. Most of the projects work fine with enunciate 2.0.0-M.3 but one requires enunciate-gwt-rt and enunciate-gwt. This project creates mapper classes to go from HyperJAXB generated beans to GWT-RPC compliant beans.
I see from the roadmap that you have not committed to updating the GWT modules. Do you have any suggestions as to how we might work around this?

**Comment by stoicflame** [comment]
@markBowman I'd be open to adding the GWT RPC module to a future Enunciate release; it's just not (currently) scheduled for inclusion in version 2.0.0.

A few questions:

* Enunciate 1's GWT module generates the mappings between a SOAP interface and a GWT-RPC interface. Do you need to keep the SOAP interface?
* Are the HyperJAXB beans not compliant with GWT RPC? Could your interface be simplified by surfacing the HyperJAXB beans directly?

**Comment by stoicflame** [comment]
[Enunciate 2.0 Milestone 4 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4) and includes:

* All the features of 2.0 Milestone 1
* All the features of 2.0 Milestone 2
* All the features of 2.0 Milestone 3
* [A bunch of bug fixes](https://github.com/stoicflame/enunciate/issues?q=milestone%3Av2.0.0.M4) (and appreciation for those who reported them)
* Support for generating the GWT JSON Overlays
* Enabled some testing that has been disabled since the branch.

Please try it out and let me know what issues you see. Depending on the number and nature of bugs that get reported, this _may_ be the last milestone release before an official release candidate.

**Comment by markBowman** [comment]
> Do you need to keep the SOAP interface?

No, we don't use the SOAP interface

> Are the HyperJAXB beans not compliant with GWT RPC? Could your interface be simplified by surfacing the HyperJAXB beans directly?

HyperJAXB classes have dependencies on Hibernate annotations and Apache Commons libraries that are not translatable

**Comment by stoicflame** [comment]
Fair enough. I've opened #136 to track the work. It's currently assigned to version 2.1.

**Comment by stoicflame** [comment]
Given the [issues reported with Milestone 4](https://github.com/stoicflame/enunciate/issues?q=milestone%3Av2.0.0-M.5+is%3Aclosed), I decided to cut [Milestone 5](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.5), which is now available. Please continue to report any issues as we try to stabilize for the first release candidate.

**Comment by stoicflame** [comment]
I finally finished the documentation overhaul for Enunciate 2. Here are some of the most relevant pages:

* [Enunciate 2 Home](https://github.com/stoicflame/enunciate/wiki/Enunciate-2)
* [Enunciate 2: Getting Started](https://github.com/stoicflame/enunciate-sample)
* [Enunciate 2 User Guide](https://github.com/stoicflame/enunciate/wiki/User-Guide)
* [Invoking Enunciate 2](https://github.com/stoicflame/enunciate/wiki/Executables)
* [Enunciate 2 Modules](https://github.com/stoicflame/enunciate/wiki/Modules)
* [Migrating from Enunciate 1.x](https://github.com/stoicflame/enunciate/wiki/Migration-Guide)
* [Enunciate 2 and Multi-Module Projects](https://github.com/stoicflame/enunciate/wiki/Multi-Module-Projects)

**Comment by stoicflame** [comment]
[Release Candidate 1 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-RC.1).

Depending on how many issues come in, I expect to release Enunciate 2.0.0 next week.

**Comment by stoicflame** [comment]
With pride and relief, I'm happy to announce the availability of [Enunciate 2.0.0](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0) and to finally close this issue.

Many thanks to everybody who contributed feedback and bugs to get us to this point.

**Comment by cforce** [comment]
can 't find it on maven central ..

**Comment by stolp** [comment]
http://search.maven.org is indeed showing 2.0.0-M.5 as the latest release when searching for com.webcohesion.enunciate. If you enter one of the artifact version lists you will spot the other releases as well (2.0.0-RC.1 and 2.0.0).

**Comment by ganeshnavdurge** [comment]
Hi Sir ,

We have developed some framework using java 6 and maven. Now we are upgrading that but when we change the dependency for tools.jar from java 6 to java 8 we are getting compilation error at AnnotationProcessorFactory because in java 8 tools.jar com.sun.mirror package is missing which was in java 6 tools.jar.

Could you please suggest the way so that i can continue upgrade with java 8 .

What i tried :

I tried by adding apt-mirror-api-0.1.jar but that was not worked.

Please suggest.

Thanks in Advanced.

Thanks,
Ganesh N.
